"""core_add_farm_field_zone_tables

Revision ID: 1087b35b8482
Revises: b4af06ada005
Create Date: 2026-07-14 18:25:30.614084

"""
import uuid
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1087b35b8482'
down_revision: Union[str, None] = 'b4af06ada005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

FARM_ID = uuid.UUID("11111111-1111-1111-1111-111111111111")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('fields',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('area_ha', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['core.farms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_fields_farm_id'), 'fields', ['farm_id'], unique=False, schema='core')
    op.create_table('zones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('field_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('area_ha', sa.Float(), nullable=False),
    sa.Column('crop', sa.String(length=128), nullable=True),
    sa.Column('irrigation_system_type', sa.Enum('drip', 'sprinkler', 'flood', 'none', name='irrigationsystemtype', native_enum=False, length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['core.fields.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_zones_field_id'), 'zones', ['field_id'], unique=False, schema='core')
    # ### end Alembic commands ###

    # --- manual addition: seed the single Farm row ---
    farms_table = sa.table(
        "farms",
        sa.column("id", sa.Uuid()),
        sa.column("name", sa.String()),
        sa.column("created_at", sa.DateTime(timezone=True)),
        schema="core",
    )
    op.bulk_insert(
        farms_table,
        [{"id": FARM_ID, "name": "Ridgeline Farm", "created_at": datetime.now(timezone.utc)}],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_core_zones_field_id'), table_name='zones', schema='core')
    op.drop_table('zones', schema='core')
    op.drop_index(op.f('ix_core_fields_farm_id'), table_name='fields', schema='core')
    op.drop_table('fields', schema='core')
    op.drop_table('farms', schema='core')
    # ### end Alembic commands ###
