"""core_add_user_language_and_settings

Revision ID: 72770b061d05
Revises: 1087b35b8482
Create Date: 2026-07-14 18:56:14.980091

"""
import uuid
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72770b061d05'
down_revision: Union[str, None] = '1087b35b8482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

SETTINGS_ID = uuid.UUID("22222222-2222-2222-2222-222222222222")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('kc_establishment', sa.Float(), nullable=False),
    sa.Column('kc_midseason', sa.Float(), nullable=False),
    sa.Column('kc_lateseason', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.add_column('users', sa.Column('preferred_language', sa.String(length=8), server_default='en', nullable=False), schema='core')
    # ### end Alembic commands ###

    # --- manual addition: seed the single Settings row (defaults match
    # Farm.Irrigation.Calculators/Presets.cs's CropCoefficients exactly) ---
    settings_table = sa.table(
        "settings",
        sa.column("id", sa.Uuid()),
        sa.column("timezone", sa.String()),
        sa.column("kc_establishment", sa.Float()),
        sa.column("kc_midseason", sa.Float()),
        sa.column("kc_lateseason", sa.Float()),
        sa.column("created_at", sa.DateTime(timezone=True)),
        schema="core",
    )
    op.bulk_insert(
        settings_table,
        [{
            "id": SETTINGS_ID,
            "timezone": "Africa/Johannesburg",
            "kc_establishment": 0.50,
            "kc_midseason": 1.05,
            "kc_lateseason": 0.80,
            "created_at": datetime.now(timezone.utc),
        }],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_language', schema='core')
    op.drop_table('settings', schema='core')
    # ### end Alembic commands ###
