"""irrigation_add_calculation_runs

Revision ID: dcb272fe5973
Revises: 72770b061d05
Create Date: 2026-07-15 16:35:52.949419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dcb272fe5973'
down_revision: Union[str, None] = '72770b061d05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS irrigation")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculation_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=False),
    sa.Column('calculator_type', sa.Enum('et0-run-time', 'manual-volume', 'drip-emitter', 'set-time', name='calculatortype', native_enum=False, length=32), nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='irrigation'
    )
    op.create_index(op.f('ix_irrigation_calculation_runs_zone_id'), 'calculation_runs', ['zone_id'], unique=False, schema='irrigation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_irrigation_calculation_runs_zone_id'), table_name='calculation_runs', schema='irrigation')
    op.drop_table('calculation_runs', schema='irrigation')
    # ### end Alembic commands ###

    op.execute("DROP SCHEMA IF EXISTS irrigation")
