"""irrigation_add_zone_design_version

Revision ID: f809d55afea7
Revises: fe4cef4d92c5
Create Date: 2026-07-17 13:36:07.987666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f809d55afea7'
down_revision: Union[str, None] = 'fe4cef4d92c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zone_design_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('design', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='irrigation'
    )
    op.create_index(op.f('ix_irrigation_zone_design_versions_zone_id'), 'zone_design_versions', ['zone_id'], unique=False, schema='irrigation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_irrigation_zone_design_versions_zone_id'), table_name='zone_design_versions', schema='irrigation')
    op.drop_table('zone_design_versions', schema='irrigation')
    # ### end Alembic commands ###
