"""core_add_zone_irrigation_interval

Revision ID: fe4cef4d92c5
Revises: dcb272fe5973
Create Date: 2026-07-15 17:50:55.997229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe4cef4d92c5'
down_revision: Union[str, None] = 'dcb272fe5973'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zones', sa.Column('irrigation_interval_days', sa.Integer(), nullable=True), schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zones', 'irrigation_interval_days', schema='core')
    # ### end Alembic commands ###
