"""irrigation_add_schedules

Revision ID: ffab7af3eca1
Revises: f809d55afea7
Create Date: 2026-07-17 21:06:29.981613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffab7af3eca1'
down_revision: Union[str, None] = 'f809d55afea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=False),
    sa.Column('available_water_mm_per_metre', sa.Float(), nullable=False),
    sa.Column('root_depth_metres', sa.Float(), nullable=False),
    sa.Column('allowable_depletion_percent', sa.Float(), nullable=False),
    sa.Column('peak_water_use_mm_per_day', sa.Float(), nullable=False),
    sa.Column('interval_days', sa.Float(), nullable=False),
    sa.Column('readily_available_water_mm', sa.Float(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='irrigation'
    )
    op.create_index(op.f('ix_irrigation_schedules_zone_id'), 'schedules', ['zone_id'], unique=True, schema='irrigation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_irrigation_schedules_zone_id'), table_name='schedules', schema='irrigation')
    op.drop_table('schedules', schema='irrigation')
    # ### end Alembic commands ###
